project_id = "ourfwvlbeokoxfgftyrs"

[functions.admin-create-user]
verify_jwt = false

[functions.ambient-voice-processor]
verify_jwt = false

[functions.elevenlabs-session]
verify_jwt = false

[functions.log-phi-access]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.emr-proxy]
verify_jwt = true